application: sample-app
version: 1
runtime: python
api_version: 1

handlers:
- url: /js
  static_dir: js
  
- url: /stylesheets
  static_dir: stylesheets
 
- url: /template
  script: template_demo.py
  
- url: /test
  script: test.py
  
- url: /course
  script: data_module.py

- url: /course/
  script: data_module.py
  
- url: /course/.*
  script: data_module.py
   
- url: /.*
  script: helloworld.py



error_handlers:
- file: default_error.html

- error_code: over_quota
  file: over_qoute.html